-- Minimal Snowflake warehouse contract used by SnowflakeDataProvider.
CREATE TABLE IF NOT EXISTS HISTORICAL_MARKET_PRICES (
    TICKER VARCHAR NOT NULL,
    OBSERVED_AT TIMESTAMP_NTZ NOT NULL,
    CLOSE_PRICE FLOAT NOT NULL,
    SOURCE VARCHAR NOT NULL,
    PRIMARY KEY (TICKER, OBSERVED_AT)
);

CREATE TABLE IF NOT EXISTS ETF_HOLDINGS (
    ETF_TICKER VARCHAR NOT NULL,
    SECURITY_TICKER VARCHAR NOT NULL,
    WEIGHT FLOAT NOT NULL,
    SECTOR VARCHAR,
    COUNTRY VARCHAR,
    AS_OF DATE NOT NULL,
    SOURCE VARCHAR NOT NULL,
    PRIMARY KEY (ETF_TICKER, SECURITY_TICKER, AS_OF)
);

CREATE TABLE IF NOT EXISTS MACRO_OBSERVATIONS (
    SERIES_ID VARCHAR NOT NULL,
    OBSERVED_AT DATE NOT NULL,
    VALUE FLOAT NOT NULL,
    SOURCE VARCHAR NOT NULL,
    PRIMARY KEY (SERIES_ID, OBSERVED_AT)
);

CREATE TABLE IF NOT EXISTS MARKET_EVIDENCE (
    EVIDENCE_ID VARCHAR NOT NULL,
    TITLE VARCHAR NOT NULL,
    EXCERPT VARCHAR NOT NULL,
    SOURCE VARCHAR NOT NULL,
    OBSERVED_AT TIMESTAMP_NTZ NOT NULL,
    URI VARCHAR,
    PRIMARY KEY (EVIDENCE_ID)
);
